### ISSUE TITLE
public forms doesn't work in my custom plugin

### ISSUE THREAD

**Issue by snailcatcher** [trendschau/typemill#493]
Hi at all,

I try to implement an order system for day tickets for an non-profit association I'm in, but I cant get the order from to work. I constantly receive `127.0.0.1:57919 [500]: GET /tageskarten - Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /.../system/typemill/Models/Fields.php on line 32` when i try to open `http://0.0.0.0:8080/tageskarten``

I started my server with `php -S 0.0.0.0:8080 `

My system:
macOS 14.6.1
PHP 8.3.12
Composer version 2.8.0
Typemill 2.9.0

Tageskarten.yaml
```yaml

name: Tageskarten
version: 0.0.1
description: Bestellsystem für Tageskarten
author: Me

public:
  fields:
    personal_fieldset:
      type: fieldset
      legend: 'Persönliche Daten'
      fields:
        firstname:
          type: text
          label: 'Vorname'
          required: true
        lastname:
          type: text
          label: 'Nachname'
          required: true
        postalcode:
          type: text
          label: 'PLZ'
          required: true
        city:
          type: text
          label: 'Ort'
          required: true
        email:
          type: email
          label: 'Email Adresse'
          required: true
    booking_fieldset:
      type: fieldset
      legend: 'Bestellung'
      fields:
        date:
          type: date
          label: 'Datum'
          required: true
        paymentmode:
          type: select
          label: 'Zahlungsart'
          required: true
          options:
            paypal: 'PayPal'
    button_label:
      type: text
      label: 'Bestellung abschicken'
      placeholder: 'Bestellung abschicken'
      required: true
```

Tageskarten.php
```php
<?php

namespace Plugins\Tageskarten;

use Typemill\Plugin;

class Tageskarten extends Plugin
{
    public static function getSubscribedEvents()
    {
        return [];
    }

    public static function addNewRoutes()
    {
        return [
            [
                'name'          => 'tageskarten.showOrderForm',
                'httpMethod'    => 'get',
                'route'         => '/tageskarten',
                'class'         => 'Plugins\Tageskarten\Tageskarten:showOrderForm'
            ],
            [
                'name'          => 'tageskarten.processOrder',
                'httpMethod'    => 'post',
                'route'         => '/tageskarten/processorder',
                'class'         => 'Plugins\Tageskarten\Tageskarten:processOrder'
            ],
        ];
    }

    public function showOrderForm($request, $response, $args)
    {
        $twig   = $this->getTwig();  // get the twig-object
        $loader = $twig->getLoader();  // get the twig-template-loader  
        $loader->addPath(__DIR__ . '/templates');
        $settings = $this->getSettings();
        $orderform = $this->generateForm('tageskarten.processOrder');
        return $twig->render($response, '/orderform.twig', ['settings' => $settings, 'orderform' => $orderform ]);
    }

    public function processOrder($request, $response, $args)
    {       
        $params = $this->validateParams($request->getParams());
        if(!$params)
        {
            return $response->withRedirect($this->container['router']->pathFor('tageskarten.showOrderForm'));
        }
        return $response->withRedirect($this->container['router']->pathFor('welcome'));
    }
}
```

templates/orderform.twig
```twig
{% extends 'layouts/layoutAuth.twig' %}
{% block title %}{{ settings.plugins.tageskarten.registerheadline|default("Tageskartenbestellung") }}{% endblock %}

{% block content %}

	<div class="orderWrapper">
		<div class="orderFormWrapper">
			<header class="orderHeader">
				<h1>{{ settings.plugins.tageskarten.registerheadline|default("Tageskartenbestellung") }}</h1>
				{% if settings.plugins.tageskarten.orderformdescription %}
					<p>{{ markdown(settings.plugins.tageskarten.orderformdescription) }}</p>
				{% endif %}
			</header>

			{{ orderform }}
		</div>
	</div>
	
{% endblock %}
```

But i found out one thing which leads me to think there must be a recursion issue or a endless loop. If I add `				print_r($fieldset['legend']);` in line 37 of `system/typemill/Models/Fields.php`:
```text
Persönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche DatenPersönliche ...
```

This will be printed forever until i stop my server (or maybe may memory overflows).

Please help me, I don't get what im doing wrong. And I think that I don't have too few memory, because the form does not have much in it.

Sincerely snailcatcher
